# Generated by Django 5.1.1 on 2024-10-27 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productpage', '0001_initial'),
        ('storepage', '0006_alter_toko_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='products_in_store', to='productpage.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.ManyToManyField(related_name='products', to='storepage.toko'),
        ),
    ]
