# Generated by Django 5.1.1 on 2024-10-25 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productpage', '0003_toko_alter_product_rating_product_store_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=20),
        ),
    ]
