# Generated by Django 5.1 on 2024-10-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productpage', '0003_remove_product_image_remove_product_num_reviews_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=None, upload_to='product_images/'),
        ),
    ]
