# Generated by Django 5.1 on 2024-10-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productpage', '0004_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/avatars/defaults.jpeg', upload_to='product_images/'),
        ),
    ]
