# Generated by Django 5.1.2 on 2024-10-27 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productpage', '0003_favorite'),
        ('productpage', '0005_toko_alter_product_image_product_store'),
    ]

    operations = [
    ]
