# Generated by Django 5.1 on 2024-10-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productpage', '0007_delete_toko_alter_product_store'),
        ('storepage', '0002_toko_delete_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.ManyToManyField(related_name='products', to='storepage.toko'),
        ),
    ]