# Generated by Django 5.1.2 on 2024-10-27 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productpage', '0006_merge_20241027_0922'),
        ('productpage', '0008_alter_product_store'),
    ]

    operations = [
    ]
