# Generated by Django 5.1 on 2024-10-27 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productpage', '0012_alter_product_category'),
        ('storepage', '0008_alter_toko_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='products_in_store', to='productpage.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='/avatars/defaults.jpeg', upload_to='images/products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='store',
            field=models.ManyToManyField(related_name='products', to='storepage.toko'),
        ),
    ]
