# Generated by Django 5.1 on 2024-10-26 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminDashboard', '0004_rename_product_store_products_remove_product_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminDashboard.rating'),
        ),
    ]
