# Generated by Django 5.1.1 on 2024-10-24 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('hari_buka', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('telepon', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Toko',
            },
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
