# Generated by Django 5.1.1 on 2024-10-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storepage', '0003_toko_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='toko',
            name='gmaps_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='toko',
            name='page_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
