# Generated by Django 5.1.1 on 2024-10-27 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storepage', '0004_toko_gmaps_link_toko_page_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toko',
            name='page_link',
        ),
        migrations.AlterField(
            model_name='toko',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='store_images/'),
        ),
    ]
