# Generated by Django 5.1.1 on 2024-10-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storepage', '0005_remove_toko_page_link_alter_toko_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toko',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
