# Generated by Django 5.1.1 on 2024-10-27 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storepage', '0006_alter_toko_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toko',
            options={},
        ),
    ]
