# Generated by Django 5.1 on 2024-10-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storepage', '0007_alter_toko_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toko',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
