# Generated by Django 5.1.2 on 2024-10-24 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forumandreviewpage', '0002_comment_postforum_delete_forumandreview_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postforum',
            name='upvotes',
        ),
    ]
