# Generated by Django 5.1.2 on 2024-10-27 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forumandreviewpage', '0004_postforum_upvotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='postforum',
            name='total_upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
