# Generated by Django 5.1.2 on 2024-10-27 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewpage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='helpful_count',
        ),
        migrations.RemoveField(
            model_name='review',
            name='unhelpful_count',
        ),
        migrations.AddField(
            model_name='review',
            name='helpful',
            field=models.ManyToManyField(blank=True, related_name='review_helpful', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='total_helpful',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='total_unhelpful',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='unhelpful',
            field=models.ManyToManyField(blank=True, related_name='review_unhelpful', to=settings.AUTH_USER_MODEL),
        ),
    ]
