<<<<<<< HEAD
# Generated by Django 5.1.2 on 2024-10-24 14:53
=======
# Generated by Django 5.1 on 2024-10-24 04:23
>>>>>>> e116997b4ff3c2d496005cac533defbaeaa757c5

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_profile_birth_date_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='static/avatars/defaults.jpeg', upload_to='static/avatars/'),
        ),
    ]
